[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
freedesktop-file-parser = "0.3.1"
nucleo-matcher = "0.3.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
